name: Deploy & Run ETL Pipeline

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - run: databricks bundle validate

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Deploy bundle
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            databricks bundle deploy --target dev
          else
            databricks bundle deploy --target prod
          fi
    env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}